#!/bin/bash

##PBS -q normal
#PBS -q gpuvolta 
#PBS -l ngpus=4 
#PBS -l ncpus=48
#PBS -l mem=128gb
#PBS -l walltime=2:00:00
#PBS -l storage=gdata/wa66

##You can use double hash symbols (##) for comment lines.

cd /g/data/wa66/erin/honours/subreddits
source venv/new/bin/activate
module unload python3
module load tensorflow
echo "Generating wordclouds run"
echo "Sports"
python3 new_lstm.py sports_f_res
echo "Stem"
python3 new_lstm.py stem_f_res
echo "music"
python3 new_lstm.py music_f_res
