#!/bin/bash

##PBS -q normal
#PBS -q gpuvolta 
#PBS -l ngpus=4
#PBS -l ncpus=48
#PBS -l mem=128gb
#PBS -l walltime=12:00:00
#PBS -l storage=gdata/wa66

##You can use double hash symbols (##) for comment lines.
cd /g/data/wa66/erin/honours/subreddits
source venv/new/bin/activate
module unload python3
module load tensorflow
echo "oldrel"
python3 sent.py rel_domain reddit_dataset_rel_75 rel
echo "sentiment assignment done"
python3 new_lstm.py rel_res 




