#!/bin/bash

##PBS -q normal
#PBS -q gpuvolta 
#PBS -l ngpus=4
#PBS -l ncpus=48
#PBS -l mem=128gb
#PBS -l walltime=24:00:00
#PBS -l storage=gdata/wa66

##You can use double hash symbols (##) for comment lines.
cd /g/data/wa66/erin/honours/subreddits
source venv/new/bin/activate
module unload python3
module load tensorflow
echo "rel multirun "
#python3 filereader.py rel_f  amiugly askmen askwomen casualiama makeupaddiction offmychest rateme loseit mensrights gonewild okcupid relationship_advice relationships sex childfree twoxchromosomes trollxchromosomes tifu teenagers christianity clubteen friendsafari gaybros lewronggeneration malefashionadvice nofap parenting raisedbynarcissists skincareaddiction talesfromretail talesfromtechsupport babybumps
#echo "Partition A"
#python3 sent.py rel_f_domain rel_sml_a rel_f_a
#echo "sentiment assignment done"
#python3 new_lstm.py rel_f_a_res
#echo "Partition B"
#python3 sent.py rel_f_domain rel_sml_b rel_f_b
#echo "sentiment assignment done"
#python3 new_lstm.py rel_f_b_res  
echo "Partition C"
python3 sent.py rel_f_domain rel_sml_c rel_f_c
echo "sentiment assignment done"
python3 new_lstm.py rel_f_c_res 
echo "Partition D"
python3 sent.py rel_f_domain rel_sml_d rel_f_d
echo "sentiment assignment done"
python3 new_lstm.py rel_f_d_res 


